------------------------------------------------------------
C:\Python27\Scripts\pip run on 06/11/15 09:55:57
Downloading/unpacking py2exe
  Getting page https://pypi.python.org/simple/py2exe/
  URLs to search for versions for py2exe:
  * https://pypi.python.org/simple/py2exe/
  Analyzing links from page https://pypi.python.org/simple/py2exe/
    Skipping https://pypi.python.org/packages/3.4/p/py2exe/py2exe-0.9.2.0-py33.py34-none-any.whl#md5=9c86adc1467b6acd0921163d79fa939f (from https://pypi.python.org/simple/py2exe/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/3.4/p/py2exe/py2exe-0.9.2.2-py33.py34-none-any.whl#md5=388c1f78d38d01e0817f08618ffdf534 (from https://pypi.python.org/simple/py2exe/) because it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/any/p/py2exe/py2exe-0.9.2.0.win-amd64.exe#md5=05d90513c993b2f3ae0f7f21d69a6898 (from https://pypi.python.org/simple/py2exe/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/p/py2exe/py2exe-0.9.2.0.win32.exe#md5=90fe08aa4ed7ab8f6b487d1fd5f45128 (from https://pypi.python.org/simple/py2exe/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/p/py2exe/py2exe-0.9.2.2.win-amd64.exe#md5=3bd1d896ad3987e5de1b3053b0985ada (from https://pypi.python.org/simple/py2exe/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/p/py2exe/py2exe-0.9.2.2.win32.exe#md5=f1684d39de2ed8287a0a36eb241f81e5 (from https://pypi.python.org/simple/py2exe/); unknown archive format: .exe
    Found link https://pypi.python.org/packages/source/p/py2exe/py2exe-0.9.2.0.zip#md5=56357f14838f616d4265e004036bb89a (from https://pypi.python.org/simple/py2exe/), version: 0.9.2.0
    Found link https://pypi.python.org/packages/source/p/py2exe/py2exe-0.9.2.2.zip#md5=f7d7e3980a606b4ded4d98016759d557 (from https://pypi.python.org/simple/py2exe/), version: 0.9.2.2
    Skipping link http://sourceforge.net/project/showfiles.php?group_id=15583 (from https://pypi.python.org/simple/py2exe/); unknown archive format: .php
    Skipping link http://starship.python.net/crew/theller/py2exe/ (from https://pypi.python.org/simple/py2exe/); not a file
    Skipping link http://www.py2exe.org (from https://pypi.python.org/simple/py2exe/); not a file
    Skipping link http://www.py2exe.org/ (from https://pypi.python.org/simple/py2exe/); not a file
  Not searching http://sourceforge.net/project/showfiles.php?group_id=15583 (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://sourceforge.net/project/showfiles.php?group_id=15583 (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://sourceforge.net/project/showfiles.php?group_id=15583 (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://sourceforge.net/project/showfiles.php?group_id=15583 (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://sourceforge.net/project/showfiles.php?group_id=15583 (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://sourceforge.net/project/showfiles.php?group_id=15583 (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://starship.python.net/crew/theller/py2exe/ (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://www.py2exe.org/ (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://www.py2exe.org/ (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://www.py2exe.org/ (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://www.py2exe.org/ (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://www.py2exe.org/ (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://www.py2exe.org/ (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Not searching http://www.py2exe.org/ (from https://pypi.python.org/simple/py2exe/) for files because external urls are disallowed.
  Using version 0.9.2.2 (newest of versions: 0.9.2.2, 0.9.2.0)
  Downloading from URL https://pypi.python.org/packages/source/p/py2exe/py2exe-0.9.2.2.zip#md5=f7d7e3980a606b4ded4d98016759d557 (from https://pypi.python.org/simple/py2exe/)
  Running setup.py (path:c:\users\vinay~1.kee\appdata\local\temp\pip_build_vinay.keerthi\py2exe\setup.py) egg_info for package py2exe
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "c:\users\vinay~1.kee\appdata\local\temp\pip_build_vinay.keerthi\py2exe\setup.py", line 10, in <module>
        raise RuntimeError("This package requires Python 3.3 or later")
    RuntimeError: This package requires Python 3.3 or later
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "c:\users\vinay~1.kee\appdata\local\temp\pip_build_vinay.keerthi\py2exe\setup.py", line 10, in <module>

    raise RuntimeError("This package requires Python 3.3 or later")

RuntimeError: This package requires Python 3.3 or later

----------------------------------------
Cleaning up...
  Removing temporary dir c:\users\vinay~1.kee\appdata\local\temp\pip_build_vinay.keerthi...
Command python setup.py egg_info failed with error code 1 in c:\users\vinay~1.kee\appdata\local\temp\pip_build_vinay.keerthi\py2exe
Exception information:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "C:\Python27\lib\site-packages\pip\req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Python27\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in c:\users\vinay~1.kee\appdata\local\temp\pip_build_vinay.keerthi\py2exe
